= A tour through a small Gradle-Groovy project
Duncan Dickinson <duncan@groovy-tutorial.org>
v0.1-DRAFT, 2015-09-15
:groovy-version: 2.4.4
:licence: Apache License, Version 2.0
:licence-url: http://www.apache.org/licenses/LICENSE-2.0
:src: https://github.com/groovy-tutorial/shapes-demo
:sourcedir: ../../main/groovy
:testdir: ../../test/groovy
:level: basic
:keywords: gradle, groovy, oo
:description:
:icons: font
:source-highlighter: coderay
:source-language: groovy
:toc:

{description}

== Introduction
This is an introductory project that demonstrates aspects of OO-programming in Groovy. The code here is described in the
https://leanpub.com/groovytutorial[The Groovy 2 Tutorial] book.

This codebase contains:

* Various http://gradle.org/[Gradle-related] files (e.g. `build.gradle`)
* Groovy source code in `src/main/groovy`
* http://spockframework.github.io/spock/docs/1.0/index.html[Spock tests] in `src/test/groovy`

You don't need Groovy or Gradle to run this codebase - you just need to have a Java JDK installed (at least v1.7).

=== Using this tutorial
Access the source code:

* {src}/tree/gh-pages[Source code on GitHub]
* {src}/archive/gh-pages.zip[As a zip file]

The code in this tutorial was prepared using Groovy version {groovy-version} and is licensed under {licence-url}[{licence}]

== Resources

* link:reports/buildDashboard/index.html[Links to the test and codenarc reports]
* link:api/groovydoc/index.html[The GroovyDoc]
* Project reports:
** link:reports/project/properties.txt[The Gradle project properties (text file)]
** link:reports/project/tasks.txt[The available Gradle tasks (text file)]
** The dependencies report (link:reports/project/dependencies/index.html[html])(link:reports/project/dependencies[text file])
* link:dist/[Distribution files]

== Running the code

=== Using Gradle

The easiest way to run the code is to use the Gradle build, as defined in `build.gradle`.

You don't need to download anything for this to work as the https://docs.gradle.org/current/userguide/wrapper_plugin.html[Gradle wrapper] will download everything you need.

==== Check out the build file
If you're new to Gradle,  check out the build file via the gui: type the following commands in the same folder as
`build.gradle` is located:

For OS X, Linux and other *nix systems:

    ./gradlew --gui

For Windows:

    gradlew.bat --gui

==== Run the build file
To run the application via Gradle:

For OS X, Linux and other *nix systems:

    ./gradlew

For Windows:

    gradlew.bat

==== Gradle tasks

The Gradle build also provides a number of interesting options. In Gradle these are called _tasks_ and you can
see all of the available tasks by running `./gradlew tasks`. Here are a few tasks worth trying out:

* `./gradlew clean`: removes all of the generated files (it doesn't delete the source code)
* `./gradlew check`: runs a http://codenarc.sourceforge.net/[CodeNarc] check and the http://spockframework.github.io/spock/docs/1.0/index.html[Spock tests]
** You can find the output of these checks/tests in the `build/publish/reports/` directory - check them out in your browser.
* `./gradlew groovydoc`: will generate the GroovyDoc for the project
** The documentation is put into `build/publish/api/` and is best read in your browser
* `./gradlew assemble`: creates a number of outputs that make distributing your code possible:
** `build/publish/dist`: contains `tar` and `zip` archives that can be distributed to others, including handy scripts to start your application

==== The Über jar
I've also added in the https://github.com/johnrengelman/shadow/[Gradle Shadow] plugin as it will create an über jar - one that hold the compiled codebase and all required libraries.
To create this file, run `./gradlew shadowJar` and `build/libs/shapes-demo-1.0-SNAPSHOT-all.jar` will be created.
Take the über jar out for a spin by running: `java -jar build/libs/shapes-demo-1.0-SNAPSHOT-all.jar`.

==== The Gradle files
There are a number of files relating to the Gradle build:

* `build.gradle` is the primary file and describes what's needed to build the application
* `gradle.properties` provides information to `build.gradle`
    * I've enabled the https://docs.gradle.org/current/userguide/gradle_daemon.html[Gradle Daemon] - this creates a background process that makes it quicker to run builds.
* `settings.gradle` is used, amongst other things, to give the project a name ("shapes-demo")
* The Gradle wrapper plugin produces the following files:
    * `gradlew` and `gradlew.bat` are used to run the Gradle build and will download a copy of Gradle if needed
    * The `gradle/wrapper` directory houses the files needed by Gradle wrapper

You'll also notice a `.gradle/` directory is created. This is used by Gradle to cache information and libraries etc.

=== Using the command line

You don't have to use the Gradle build to build and run the code and it might be a useful learning experience to try out
compiling and running the code from the command line. In order to do this you'll want to have both a JDK and Groovy installed.

The information provided here has been prepared on an OS X system
so should also work in Linux systems. Windows users will most likely need to change the file paths.

__Note:__ All commands provided in this section are run from the base of the project distribution - that's where this
README file resides.

To run the code using `groovy`:

    groovy -classpath src/main/groovy/ src/main/groovy/org/groovytutorial/shapes/app/Main.groovy

To compile the classes to bytecode and run with Java we need to use `groovyc`:

    groovyc -d classes src/main/groovy/org/groovytutorial/shapes/*.groovy src/main/groovy/org/groovytutorial/shapes/app/*.groovy src/main/groovy/org/groovytutorial/shapes/triangle/*.groovy
    java -cp lib/groovy-all-2.4.4.jar:classes/ org.groovytutorial.shapes.app.Main

To create a Jar:

    groovyc -d classes src/main/groovy/org/groovytutorial/shapes/*.groovy src/main/groovy/org/groovytutorial/shapes/app/*.groovy src/main/groovy/org/groovytutorial/shapes/triangle/*.groovy
    jar cvf lib/Shapes.jar -C classes .

To run the Jar:

    java -cp lib/groovy-all-2.4.4.jar:lib/Shapes.jar org.groovytutorial.shapes.app.Main
